# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import faceit_api
from faceit_api.api.matchmakings_api import MatchmakingsApi  # noqa: E501
from faceit_api.rest import ApiException


class TestMatchmakingsApi(unittest.TestCase):
    """MatchmakingsApi unit test stubs"""

    def setUp(self):
        self.api = faceit_api.api.matchmakings_api.MatchmakingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_matchmaking(self):
        """Test case for get_matchmaking

        Retrieve details of a matchmaking of a game on FACEIT  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
