# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import faceit_api
from faceit_api.api.search_api import SearchApi  # noqa: E501
from faceit_api.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = faceit_api.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_championships(self):
        """Test case for search_championships

        Search for championships  # noqa: E501
        """
        pass

    def test_search_clans(self):
        """Test case for search_clans

        Search for clans  # noqa: E501
        """
        pass

    def test_search_hubs(self):
        """Test case for search_hubs

        Search for hubs  # noqa: E501
        """
        pass

    def test_search_organizers(self):
        """Test case for search_organizers

        Search for organizers  # noqa: E501
        """
        pass

    def test_search_players(self):
        """Test case for search_players

        Search for players  # noqa: E501
        """
        pass

    def test_search_teams(self):
        """Test case for search_teams

        Search for teams  # noqa: E501
        """
        pass

    def test_search_tournaments(self):
        """Test case for search_tournaments

        Search for tournaments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
