# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import faceit_api
from faceit_api.api.organizers_api import OrganizersApi  # noqa: E501
from faceit_api.rest import ApiException


class TestOrganizersApi(unittest.TestCase):
    """OrganizersApi unit test stubs"""

    def setUp(self):
        self.api = faceit_api.api.organizers_api.OrganizersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_organizer(self):
        """Test case for get_organizer

        Retrieve organizer details  # noqa: E501
        """
        pass

    def test_get_organizer_by_name(self):
        """Test case for get_organizer_by_name

        Retrieve organizer details from name  # noqa: E501
        """
        pass

    def test_get_organizer_championships(self):
        """Test case for get_organizer_championships

        Retrieve all championships of an organizer  # noqa: E501
        """
        pass

    def test_get_organizer_games(self):
        """Test case for get_organizer_games

        Retrieve all games an organizer is involved with  # noqa: E501
        """
        pass

    def test_get_organizer_hubs(self):
        """Test case for get_organizer_hubs

        Retrieve all hubs of an organizer  # noqa: E501
        """
        pass

    def test_get_organizer_tournaments(self):
        """Test case for get_organizer_tournaments

        Retrieve all tournaments of an organizer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
