# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import faceit_api
from faceit_api.api.rankings_api import RankingsApi  # noqa: E501
from faceit_api.rest import ApiException


class TestRankingsApi(unittest.TestCase):
    """RankingsApi unit test stubs"""

    def setUp(self):
        self.api = faceit_api.api.rankings_api.RankingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_global_ranking(self):
        """Test case for get_global_ranking

        Retrieve global ranking of a game  # noqa: E501
        """
        pass

    def test_get_player_ranking(self):
        """Test case for get_player_ranking

        Retrieve user position in the global ranking of a game  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
