# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import faceit_api
from faceit_api.models.queue_ban import QueueBan  # noqa: E501
from faceit_api.rest import ApiException


class TestQueueBan(unittest.TestCase):
    """QueueBan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueueBan(self):
        """Test QueueBan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = faceit_api.models.queue_ban.QueueBan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
