# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class GeoDescription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'en': 'str',
        'fr': 'str'
    }

    attribute_map = {
        'en': 'en',
        'fr': 'fr'
    }

    def __init__(self, en=None, fr=None, _configuration=None):  # noqa: E501
        """GeoDescription - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._en = None
        self._fr = None
        self.discriminator = None

        if en is not None:
            self.en = en
        if fr is not None:
            self.fr = fr

    @property
    def en(self):
        """Gets the en of this GeoDescription.  # noqa: E501


        :return: The en of this GeoDescription.  # noqa: E501
        :rtype: str
        """
        return self._en

    @en.setter
    def en(self, en):
        """Sets the en of this GeoDescription.


        :param en: The en of this GeoDescription.  # noqa: E501
        :type: str
        """

        self._en = en

    @property
    def fr(self):
        """Gets the fr of this GeoDescription.  # noqa: E501


        :return: The fr of this GeoDescription.  # noqa: E501
        :rtype: str
        """
        return self._fr

    @fr.setter
    def fr(self, fr):
        """Sets the fr of this GeoDescription.


        :param fr: The fr of this GeoDescription.  # noqa: E501
        :type: str
        """

        self._fr = fr

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeoDescription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeoDescription):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GeoDescription):
            return True

        return self.to_dict() != other.to_dict()
