# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class HistoryFaction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'avatar': 'str',
        'nickname': 'str',
        'players': 'list[MatchHistoryPlayer]',
        'team_id': 'str',
        'type': 'str'
    }

    attribute_map = {
        'avatar': 'avatar',
        'nickname': 'nickname',
        'players': 'players',
        'team_id': 'team_id',
        'type': 'type'
    }

    def __init__(self, avatar=None, nickname=None, players=None, team_id=None, type=None, _configuration=None):  # noqa: E501
        """HistoryFaction - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._avatar = None
        self._nickname = None
        self._players = None
        self._team_id = None
        self._type = None
        self.discriminator = None

        if avatar is not None:
            self.avatar = avatar
        if nickname is not None:
            self.nickname = nickname
        if players is not None:
            self.players = players
        if team_id is not None:
            self.team_id = team_id
        if type is not None:
            self.type = type

    @property
    def avatar(self):
        """Gets the avatar of this HistoryFaction.  # noqa: E501


        :return: The avatar of this HistoryFaction.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this HistoryFaction.


        :param avatar: The avatar of this HistoryFaction.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def nickname(self):
        """Gets the nickname of this HistoryFaction.  # noqa: E501


        :return: The nickname of this HistoryFaction.  # noqa: E501
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """Sets the nickname of this HistoryFaction.


        :param nickname: The nickname of this HistoryFaction.  # noqa: E501
        :type: str
        """

        self._nickname = nickname

    @property
    def players(self):
        """Gets the players of this HistoryFaction.  # noqa: E501


        :return: The players of this HistoryFaction.  # noqa: E501
        :rtype: list[MatchHistoryPlayer]
        """
        return self._players

    @players.setter
    def players(self, players):
        """Sets the players of this HistoryFaction.


        :param players: The players of this HistoryFaction.  # noqa: E501
        :type: list[MatchHistoryPlayer]
        """

        self._players = players

    @property
    def team_id(self):
        """Gets the team_id of this HistoryFaction.  # noqa: E501


        :return: The team_id of this HistoryFaction.  # noqa: E501
        :rtype: str
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this HistoryFaction.


        :param team_id: The team_id of this HistoryFaction.  # noqa: E501
        :type: str
        """

        self._team_id = team_id

    @property
    def type(self):
        """Gets the type of this HistoryFaction.  # noqa: E501


        :return: The type of this HistoryFaction.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this HistoryFaction.


        :param type: The type of this HistoryFaction.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistoryFaction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistoryFaction):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HistoryFaction):
            return True

        return self.to_dict() != other.to_dict()
