# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class HubSmall(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'avatar': 'str',
        'faceit_url': 'str',
        'game_id': 'str',
        'hub_id': 'str',
        'name': 'str',
        'organizer_id': 'str'
    }

    attribute_map = {
        'avatar': 'avatar',
        'faceit_url': 'faceit_url',
        'game_id': 'game_id',
        'hub_id': 'hub_id',
        'name': 'name',
        'organizer_id': 'organizer_id'
    }

    def __init__(self, avatar=None, faceit_url=None, game_id=None, hub_id=None, name=None, organizer_id=None, _configuration=None):  # noqa: E501
        """HubSmall - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._avatar = None
        self._faceit_url = None
        self._game_id = None
        self._hub_id = None
        self._name = None
        self._organizer_id = None
        self.discriminator = None

        if avatar is not None:
            self.avatar = avatar
        if faceit_url is not None:
            self.faceit_url = faceit_url
        if game_id is not None:
            self.game_id = game_id
        if hub_id is not None:
            self.hub_id = hub_id
        if name is not None:
            self.name = name
        if organizer_id is not None:
            self.organizer_id = organizer_id

    @property
    def avatar(self):
        """Gets the avatar of this HubSmall.  # noqa: E501


        :return: The avatar of this HubSmall.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this HubSmall.


        :param avatar: The avatar of this HubSmall.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def faceit_url(self):
        """Gets the faceit_url of this HubSmall.  # noqa: E501


        :return: The faceit_url of this HubSmall.  # noqa: E501
        :rtype: str
        """
        return self._faceit_url

    @faceit_url.setter
    def faceit_url(self, faceit_url):
        """Sets the faceit_url of this HubSmall.


        :param faceit_url: The faceit_url of this HubSmall.  # noqa: E501
        :type: str
        """

        self._faceit_url = faceit_url

    @property
    def game_id(self):
        """Gets the game_id of this HubSmall.  # noqa: E501


        :return: The game_id of this HubSmall.  # noqa: E501
        :rtype: str
        """
        return self._game_id

    @game_id.setter
    def game_id(self, game_id):
        """Sets the game_id of this HubSmall.


        :param game_id: The game_id of this HubSmall.  # noqa: E501
        :type: str
        """

        self._game_id = game_id

    @property
    def hub_id(self):
        """Gets the hub_id of this HubSmall.  # noqa: E501


        :return: The hub_id of this HubSmall.  # noqa: E501
        :rtype: str
        """
        return self._hub_id

    @hub_id.setter
    def hub_id(self, hub_id):
        """Sets the hub_id of this HubSmall.


        :param hub_id: The hub_id of this HubSmall.  # noqa: E501
        :type: str
        """

        self._hub_id = hub_id

    @property
    def name(self):
        """Gets the name of this HubSmall.  # noqa: E501


        :return: The name of this HubSmall.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HubSmall.


        :param name: The name of this HubSmall.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def organizer_id(self):
        """Gets the organizer_id of this HubSmall.  # noqa: E501


        :return: The organizer_id of this HubSmall.  # noqa: E501
        :rtype: str
        """
        return self._organizer_id

    @organizer_id.setter
    def organizer_id(self, organizer_id):
        """Sets the organizer_id of this HubSmall.


        :param organizer_id: The organizer_id of this HubSmall.  # noqa: E501
        :type: str
        """

        self._organizer_id = organizer_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HubSmall, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HubSmall):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HubSmall):
            return True

        return self.to_dict() != other.to_dict()
