# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class HubUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'avatar': 'str',
        'faceit_url': 'str',
        'nickname': 'str',
        'roles': 'list[str]',
        'user_id': 'str'
    }

    attribute_map = {
        'avatar': 'avatar',
        'faceit_url': 'faceit_url',
        'nickname': 'nickname',
        'roles': 'roles',
        'user_id': 'user_id'
    }

    def __init__(self, avatar=None, faceit_url=None, nickname=None, roles=None, user_id=None, _configuration=None):  # noqa: E501
        """HubUser - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._avatar = None
        self._faceit_url = None
        self._nickname = None
        self._roles = None
        self._user_id = None
        self.discriminator = None

        if avatar is not None:
            self.avatar = avatar
        if faceit_url is not None:
            self.faceit_url = faceit_url
        if nickname is not None:
            self.nickname = nickname
        if roles is not None:
            self.roles = roles
        if user_id is not None:
            self.user_id = user_id

    @property
    def avatar(self):
        """Gets the avatar of this HubUser.  # noqa: E501


        :return: The avatar of this HubUser.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this HubUser.


        :param avatar: The avatar of this HubUser.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def faceit_url(self):
        """Gets the faceit_url of this HubUser.  # noqa: E501


        :return: The faceit_url of this HubUser.  # noqa: E501
        :rtype: str
        """
        return self._faceit_url

    @faceit_url.setter
    def faceit_url(self, faceit_url):
        """Sets the faceit_url of this HubUser.


        :param faceit_url: The faceit_url of this HubUser.  # noqa: E501
        :type: str
        """

        self._faceit_url = faceit_url

    @property
    def nickname(self):
        """Gets the nickname of this HubUser.  # noqa: E501


        :return: The nickname of this HubUser.  # noqa: E501
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """Sets the nickname of this HubUser.


        :param nickname: The nickname of this HubUser.  # noqa: E501
        :type: str
        """

        self._nickname = nickname

    @property
    def roles(self):
        """Gets the roles of this HubUser.  # noqa: E501


        :return: The roles of this HubUser.  # noqa: E501
        :rtype: list[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this HubUser.


        :param roles: The roles of this HubUser.  # noqa: E501
        :type: list[str]
        """

        self._roles = roles

    @property
    def user_id(self):
        """Gets the user_id of this HubUser.  # noqa: E501


        :return: The user_id of this HubUser.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this HubUser.


        :param user_id: The user_id of this HubUser.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HubUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HubUser):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HubUser):
            return True

        return self.to_dict() != other.to_dict()
