# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class HubStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'game_id': 'str',
        'players': 'list[StatsCompetitionPlayer]'
    }

    attribute_map = {
        'game_id': 'game_id',
        'players': 'players'
    }

    def __init__(self, game_id=None, players=None, _configuration=None):  # noqa: E501
        """HubStats - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._game_id = None
        self._players = None
        self.discriminator = None

        if game_id is not None:
            self.game_id = game_id
        if players is not None:
            self.players = players

    @property
    def game_id(self):
        """Gets the game_id of this HubStats.  # noqa: E501


        :return: The game_id of this HubStats.  # noqa: E501
        :rtype: str
        """
        return self._game_id

    @game_id.setter
    def game_id(self, game_id):
        """Sets the game_id of this HubStats.


        :param game_id: The game_id of this HubStats.  # noqa: E501
        :type: str
        """

        self._game_id = game_id

    @property
    def players(self):
        """Gets the players of this HubStats.  # noqa: E501


        :return: The players of this HubStats.  # noqa: E501
        :rtype: list[StatsCompetitionPlayer]
        """
        return self._players

    @players.setter
    def players(self, players):
        """Sets the players of this HubStats.


        :param players: The players of this HubStats.  # noqa: E501
        :type: list[StatsCompetitionPlayer]
        """

        self._players = players

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HubStats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HubStats):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HubStats):
            return True

        return self.to_dict() != other.to_dict()
