# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class MatchmakingSlim(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'game': 'str',
        'has_league': 'bool',
        'id': 'str',
        'name': 'str',
        'region': 'str'
    }

    attribute_map = {
        'game': 'game',
        'has_league': 'has_league',
        'id': 'id',
        'name': 'name',
        'region': 'region'
    }

    def __init__(self, game=None, has_league=None, id=None, name=None, region=None, _configuration=None):  # noqa: E501
        """MatchmakingSlim - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._game = None
        self._has_league = None
        self._id = None
        self._name = None
        self._region = None
        self.discriminator = None

        if game is not None:
            self.game = game
        if has_league is not None:
            self.has_league = has_league
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if region is not None:
            self.region = region

    @property
    def game(self):
        """Gets the game of this MatchmakingSlim.  # noqa: E501


        :return: The game of this MatchmakingSlim.  # noqa: E501
        :rtype: str
        """
        return self._game

    @game.setter
    def game(self, game):
        """Sets the game of this MatchmakingSlim.


        :param game: The game of this MatchmakingSlim.  # noqa: E501
        :type: str
        """

        self._game = game

    @property
    def has_league(self):
        """Gets the has_league of this MatchmakingSlim.  # noqa: E501


        :return: The has_league of this MatchmakingSlim.  # noqa: E501
        :rtype: bool
        """
        return self._has_league

    @has_league.setter
    def has_league(self, has_league):
        """Sets the has_league of this MatchmakingSlim.


        :param has_league: The has_league of this MatchmakingSlim.  # noqa: E501
        :type: bool
        """

        self._has_league = has_league

    @property
    def id(self):
        """Gets the id of this MatchmakingSlim.  # noqa: E501


        :return: The id of this MatchmakingSlim.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MatchmakingSlim.


        :param id: The id of this MatchmakingSlim.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MatchmakingSlim.  # noqa: E501


        :return: The name of this MatchmakingSlim.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MatchmakingSlim.


        :param name: The name of this MatchmakingSlim.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def region(self):
        """Gets the region of this MatchmakingSlim.  # noqa: E501


        :return: The region of this MatchmakingSlim.  # noqa: E501
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this MatchmakingSlim.


        :param region: The region of this MatchmakingSlim.  # noqa: E501
        :type: str
        """

        self._region = region

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatchmakingSlim, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchmakingSlim):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MatchmakingSlim):
            return True

        return self.to_dict() != other.to_dict()
