# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class MatchHistoryPlayer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'avatar': 'str',
        'faceit_url': 'str',
        'game_player_id': 'str',
        'game_player_name': 'str',
        'nickname': 'str',
        'player_id': 'str',
        'skill_level': 'int'
    }

    attribute_map = {
        'avatar': 'avatar',
        'faceit_url': 'faceit_url',
        'game_player_id': 'game_player_id',
        'game_player_name': 'game_player_name',
        'nickname': 'nickname',
        'player_id': 'player_id',
        'skill_level': 'skill_level'
    }

    def __init__(self, avatar=None, faceit_url=None, game_player_id=None, game_player_name=None, nickname=None, player_id=None, skill_level=None, _configuration=None):  # noqa: E501
        """MatchHistoryPlayer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._avatar = None
        self._faceit_url = None
        self._game_player_id = None
        self._game_player_name = None
        self._nickname = None
        self._player_id = None
        self._skill_level = None
        self.discriminator = None

        if avatar is not None:
            self.avatar = avatar
        if faceit_url is not None:
            self.faceit_url = faceit_url
        if game_player_id is not None:
            self.game_player_id = game_player_id
        if game_player_name is not None:
            self.game_player_name = game_player_name
        if nickname is not None:
            self.nickname = nickname
        if player_id is not None:
            self.player_id = player_id
        if skill_level is not None:
            self.skill_level = skill_level

    @property
    def avatar(self):
        """Gets the avatar of this MatchHistoryPlayer.  # noqa: E501


        :return: The avatar of this MatchHistoryPlayer.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this MatchHistoryPlayer.


        :param avatar: The avatar of this MatchHistoryPlayer.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def faceit_url(self):
        """Gets the faceit_url of this MatchHistoryPlayer.  # noqa: E501


        :return: The faceit_url of this MatchHistoryPlayer.  # noqa: E501
        :rtype: str
        """
        return self._faceit_url

    @faceit_url.setter
    def faceit_url(self, faceit_url):
        """Sets the faceit_url of this MatchHistoryPlayer.


        :param faceit_url: The faceit_url of this MatchHistoryPlayer.  # noqa: E501
        :type: str
        """

        self._faceit_url = faceit_url

    @property
    def game_player_id(self):
        """Gets the game_player_id of this MatchHistoryPlayer.  # noqa: E501


        :return: The game_player_id of this MatchHistoryPlayer.  # noqa: E501
        :rtype: str
        """
        return self._game_player_id

    @game_player_id.setter
    def game_player_id(self, game_player_id):
        """Sets the game_player_id of this MatchHistoryPlayer.


        :param game_player_id: The game_player_id of this MatchHistoryPlayer.  # noqa: E501
        :type: str
        """

        self._game_player_id = game_player_id

    @property
    def game_player_name(self):
        """Gets the game_player_name of this MatchHistoryPlayer.  # noqa: E501


        :return: The game_player_name of this MatchHistoryPlayer.  # noqa: E501
        :rtype: str
        """
        return self._game_player_name

    @game_player_name.setter
    def game_player_name(self, game_player_name):
        """Sets the game_player_name of this MatchHistoryPlayer.


        :param game_player_name: The game_player_name of this MatchHistoryPlayer.  # noqa: E501
        :type: str
        """

        self._game_player_name = game_player_name

    @property
    def nickname(self):
        """Gets the nickname of this MatchHistoryPlayer.  # noqa: E501


        :return: The nickname of this MatchHistoryPlayer.  # noqa: E501
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """Sets the nickname of this MatchHistoryPlayer.


        :param nickname: The nickname of this MatchHistoryPlayer.  # noqa: E501
        :type: str
        """

        self._nickname = nickname

    @property
    def player_id(self):
        """Gets the player_id of this MatchHistoryPlayer.  # noqa: E501


        :return: The player_id of this MatchHistoryPlayer.  # noqa: E501
        :rtype: str
        """
        return self._player_id

    @player_id.setter
    def player_id(self, player_id):
        """Sets the player_id of this MatchHistoryPlayer.


        :param player_id: The player_id of this MatchHistoryPlayer.  # noqa: E501
        :type: str
        """

        self._player_id = player_id

    @property
    def skill_level(self):
        """Gets the skill_level of this MatchHistoryPlayer.  # noqa: E501


        :return: The skill_level of this MatchHistoryPlayer.  # noqa: E501
        :rtype: int
        """
        return self._skill_level

    @skill_level.setter
    def skill_level(self, skill_level):
        """Sets the skill_level of this MatchHistoryPlayer.


        :param skill_level: The skill_level of this MatchHistoryPlayer.  # noqa: E501
        :type: int
        """

        self._skill_level = skill_level

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatchHistoryPlayer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchHistoryPlayer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MatchHistoryPlayer):
            return True

        return self.to_dict() != other.to_dict()
