# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class MatchmakingQueue(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'open': 'bool',
        'organizer_id': 'str',
        'paused': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'open': 'open',
        'organizer_id': 'organizer_id',
        'paused': 'paused'
    }

    def __init__(self, id=None, name=None, open=None, organizer_id=None, paused=None, _configuration=None):  # noqa: E501
        """MatchmakingQueue - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._open = None
        self._organizer_id = None
        self._paused = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if open is not None:
            self.open = open
        if organizer_id is not None:
            self.organizer_id = organizer_id
        if paused is not None:
            self.paused = paused

    @property
    def id(self):
        """Gets the id of this MatchmakingQueue.  # noqa: E501


        :return: The id of this MatchmakingQueue.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MatchmakingQueue.


        :param id: The id of this MatchmakingQueue.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this MatchmakingQueue.  # noqa: E501


        :return: The name of this MatchmakingQueue.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MatchmakingQueue.


        :param name: The name of this MatchmakingQueue.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def open(self):
        """Gets the open of this MatchmakingQueue.  # noqa: E501


        :return: The open of this MatchmakingQueue.  # noqa: E501
        :rtype: bool
        """
        return self._open

    @open.setter
    def open(self, open):
        """Sets the open of this MatchmakingQueue.


        :param open: The open of this MatchmakingQueue.  # noqa: E501
        :type: bool
        """

        self._open = open

    @property
    def organizer_id(self):
        """Gets the organizer_id of this MatchmakingQueue.  # noqa: E501


        :return: The organizer_id of this MatchmakingQueue.  # noqa: E501
        :rtype: str
        """
        return self._organizer_id

    @organizer_id.setter
    def organizer_id(self, organizer_id):
        """Sets the organizer_id of this MatchmakingQueue.


        :param organizer_id: The organizer_id of this MatchmakingQueue.  # noqa: E501
        :type: str
        """

        self._organizer_id = organizer_id

    @property
    def paused(self):
        """Gets the paused of this MatchmakingQueue.  # noqa: E501


        :return: The paused of this MatchmakingQueue.  # noqa: E501
        :rtype: bool
        """
        return self._paused

    @paused.setter
    def paused(self, paused):
        """Sets the paused of this MatchmakingQueue.


        :param paused: The paused of this MatchmakingQueue.  # noqa: E501
        :type: bool
        """

        self._paused = paused

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatchmakingQueue, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchmakingQueue):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MatchmakingQueue):
            return True

        return self.to_dict() != other.to_dict()
