# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class OrderItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'external_id': 'str',
        'image_url': 'str',
        'item_id': 'str',
        'name': 'str',
        'price': 'float'
    }

    attribute_map = {
        'external_id': 'external_id',
        'image_url': 'image_url',
        'item_id': 'item_id',
        'name': 'name',
        'price': 'price'
    }

    def __init__(self, external_id=None, image_url=None, item_id=None, name=None, price=None, _configuration=None):  # noqa: E501
        """OrderItem - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._external_id = None
        self._image_url = None
        self._item_id = None
        self._name = None
        self._price = None
        self.discriminator = None

        if external_id is not None:
            self.external_id = external_id
        if image_url is not None:
            self.image_url = image_url
        if item_id is not None:
            self.item_id = item_id
        if name is not None:
            self.name = name
        if price is not None:
            self.price = price

    @property
    def external_id(self):
        """Gets the external_id of this OrderItem.  # noqa: E501


        :return: The external_id of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this OrderItem.


        :param external_id: The external_id of this OrderItem.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def image_url(self):
        """Gets the image_url of this OrderItem.  # noqa: E501


        :return: The image_url of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this OrderItem.


        :param image_url: The image_url of this OrderItem.  # noqa: E501
        :type: str
        """

        self._image_url = image_url

    @property
    def item_id(self):
        """Gets the item_id of this OrderItem.  # noqa: E501


        :return: The item_id of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this OrderItem.


        :param item_id: The item_id of this OrderItem.  # noqa: E501
        :type: str
        """

        self._item_id = item_id

    @property
    def name(self):
        """Gets the name of this OrderItem.  # noqa: E501


        :return: The name of this OrderItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OrderItem.


        :param name: The name of this OrderItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def price(self):
        """Gets the price of this OrderItem.  # noqa: E501


        :return: The price of this OrderItem.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this OrderItem.


        :param price: The price of this OrderItem.  # noqa: E501
        :type: float
        """

        self._price = price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderItem):
            return True

        return self.to_dict() != other.to_dict()
