# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class PlayerStatsSimple(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'nickname': 'object',
        'player_id': 'object',
        'player_stats': 'dict(str, object)'
    }

    attribute_map = {
        'nickname': 'nickname',
        'player_id': 'player_id',
        'player_stats': 'player_stats'
    }

    def __init__(self, nickname=None, player_id=None, player_stats=None, _configuration=None):  # noqa: E501
        """PlayerStatsSimple - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._nickname = None
        self._player_id = None
        self._player_stats = None
        self.discriminator = None

        if nickname is not None:
            self.nickname = nickname
        if player_id is not None:
            self.player_id = player_id
        if player_stats is not None:
            self.player_stats = player_stats

    @property
    def nickname(self):
        """Gets the nickname of this PlayerStatsSimple.  # noqa: E501


        :return: The nickname of this PlayerStatsSimple.  # noqa: E501
        :rtype: object
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """Sets the nickname of this PlayerStatsSimple.


        :param nickname: The nickname of this PlayerStatsSimple.  # noqa: E501
        :type: object
        """

        self._nickname = nickname

    @property
    def player_id(self):
        """Gets the player_id of this PlayerStatsSimple.  # noqa: E501


        :return: The player_id of this PlayerStatsSimple.  # noqa: E501
        :rtype: object
        """
        return self._player_id

    @player_id.setter
    def player_id(self, player_id):
        """Sets the player_id of this PlayerStatsSimple.


        :param player_id: The player_id of this PlayerStatsSimple.  # noqa: E501
        :type: object
        """

        self._player_id = player_id

    @property
    def player_stats(self):
        """Gets the player_stats of this PlayerStatsSimple.  # noqa: E501


        :return: The player_stats of this PlayerStatsSimple.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._player_stats

    @player_stats.setter
    def player_stats(self, player_stats):
        """Sets the player_stats of this PlayerStatsSimple.


        :param player_stats: The player_stats of this PlayerStatsSimple.  # noqa: E501
        :type: dict(str, object)
        """

        self._player_stats = player_stats

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlayerStatsSimple, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlayerStatsSimple):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PlayerStatsSimple):
            return True

        return self.to_dict() != other.to_dict()
