# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class Role(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'color': 'str',
        'name': 'str',
        'ranking': 'int',
        'role_id': 'str',
        'visible_on_chat': 'bool'
    }

    attribute_map = {
        'color': 'color',
        'name': 'name',
        'ranking': 'ranking',
        'role_id': 'role_id',
        'visible_on_chat': 'visible_on_chat'
    }

    def __init__(self, color=None, name=None, ranking=None, role_id=None, visible_on_chat=None, _configuration=None):  # noqa: E501
        """Role - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._color = None
        self._name = None
        self._ranking = None
        self._role_id = None
        self._visible_on_chat = None
        self.discriminator = None

        if color is not None:
            self.color = color
        if name is not None:
            self.name = name
        if ranking is not None:
            self.ranking = ranking
        if role_id is not None:
            self.role_id = role_id
        if visible_on_chat is not None:
            self.visible_on_chat = visible_on_chat

    @property
    def color(self):
        """Gets the color of this Role.  # noqa: E501


        :return: The color of this Role.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Role.


        :param color: The color of this Role.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def name(self):
        """Gets the name of this Role.  # noqa: E501


        :return: The name of this Role.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Role.


        :param name: The name of this Role.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def ranking(self):
        """Gets the ranking of this Role.  # noqa: E501


        :return: The ranking of this Role.  # noqa: E501
        :rtype: int
        """
        return self._ranking

    @ranking.setter
    def ranking(self, ranking):
        """Sets the ranking of this Role.


        :param ranking: The ranking of this Role.  # noqa: E501
        :type: int
        """

        self._ranking = ranking

    @property
    def role_id(self):
        """Gets the role_id of this Role.  # noqa: E501


        :return: The role_id of this Role.  # noqa: E501
        :rtype: str
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id):
        """Sets the role_id of this Role.


        :param role_id: The role_id of this Role.  # noqa: E501
        :type: str
        """

        self._role_id = role_id

    @property
    def visible_on_chat(self):
        """Gets the visible_on_chat of this Role.  # noqa: E501


        :return: The visible_on_chat of this Role.  # noqa: E501
        :rtype: bool
        """
        return self._visible_on_chat

    @visible_on_chat.setter
    def visible_on_chat(self, visible_on_chat):
        """Sets the visible_on_chat of this Role.


        :param visible_on_chat: The visible_on_chat of this Role.  # noqa: E501
        :type: bool
        """

        self._visible_on_chat = visible_on_chat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Role, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Role):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Role):
            return True

        return self.to_dict() != other.to_dict()
