# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class Rules(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'body': 'str',
        'game': 'str',
        'name': 'str',
        'organizer': 'str',
        'rule_id': 'str'
    }

    attribute_map = {
        'body': 'body',
        'game': 'game',
        'name': 'name',
        'organizer': 'organizer',
        'rule_id': 'rule_id'
    }

    def __init__(self, body=None, game=None, name=None, organizer=None, rule_id=None, _configuration=None):  # noqa: E501
        """Rules - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._body = None
        self._game = None
        self._name = None
        self._organizer = None
        self._rule_id = None
        self.discriminator = None

        if body is not None:
            self.body = body
        if game is not None:
            self.game = game
        if name is not None:
            self.name = name
        if organizer is not None:
            self.organizer = organizer
        if rule_id is not None:
            self.rule_id = rule_id

    @property
    def body(self):
        """Gets the body of this Rules.  # noqa: E501


        :return: The body of this Rules.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this Rules.


        :param body: The body of this Rules.  # noqa: E501
        :type: str
        """

        self._body = body

    @property
    def game(self):
        """Gets the game of this Rules.  # noqa: E501


        :return: The game of this Rules.  # noqa: E501
        :rtype: str
        """
        return self._game

    @game.setter
    def game(self, game):
        """Sets the game of this Rules.


        :param game: The game of this Rules.  # noqa: E501
        :type: str
        """

        self._game = game

    @property
    def name(self):
        """Gets the name of this Rules.  # noqa: E501


        :return: The name of this Rules.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Rules.


        :param name: The name of this Rules.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def organizer(self):
        """Gets the organizer of this Rules.  # noqa: E501


        :return: The organizer of this Rules.  # noqa: E501
        :rtype: str
        """
        return self._organizer

    @organizer.setter
    def organizer(self, organizer):
        """Sets the organizer of this Rules.


        :param organizer: The organizer of this Rules.  # noqa: E501
        :type: str
        """

        self._organizer = organizer

    @property
    def rule_id(self):
        """Gets the rule_id of this Rules.  # noqa: E501


        :return: The rule_id of this Rules.  # noqa: E501
        :rtype: str
        """
        return self._rule_id

    @rule_id.setter
    def rule_id(self, rule_id):
        """Sets the rule_id of this Rules.


        :param rule_id: The rule_id of this Rules.  # noqa: E501
        :type: str
        """

        self._rule_id = rule_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Rules, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Rules):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Rules):
            return True

        return self.to_dict() != other.to_dict()
