# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class TypeMount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fs_type': 'str',
        'mount_flags': 'list[str]'
    }

    attribute_map = {
        'fs_type': 'FsType',
        'mount_flags': 'MountFlags'
    }

    def __init__(self, fs_type=None, mount_flags=None, _configuration=None):  # noqa: E501
        """TypeMount - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._fs_type = None
        self._mount_flags = None
        self.discriminator = None

        if fs_type is not None:
            self.fs_type = fs_type
        if mount_flags is not None:
            self.mount_flags = mount_flags

    @property
    def fs_type(self):
        """Gets the fs_type of this TypeMount.  # noqa: E501

        FsType specifies the filesystem type for the mount volume. Optional.  # noqa: E501

        :return: The fs_type of this TypeMount.  # noqa: E501
        :rtype: str
        """
        return self._fs_type

    @fs_type.setter
    def fs_type(self, fs_type):
        """Sets the fs_type of this TypeMount.

        FsType specifies the filesystem type for the mount volume. Optional.  # noqa: E501

        :param fs_type: The fs_type of this TypeMount.  # noqa: E501
        :type: str
        """

        self._fs_type = fs_type

    @property
    def mount_flags(self):
        """Gets the mount_flags of this TypeMount.  # noqa: E501

        MountFlags defines flags to pass when mounting the volume. Optional.  # noqa: E501

        :return: The mount_flags of this TypeMount.  # noqa: E501
        :rtype: list[str]
        """
        return self._mount_flags

    @mount_flags.setter
    def mount_flags(self, mount_flags):
        """Sets the mount_flags of this TypeMount.

        MountFlags defines flags to pass when mounting the volume. Optional.  # noqa: E501

        :param mount_flags: The mount_flags of this TypeMount.  # noqa: E501
        :type: list[str]
        """

        self._mount_flags = mount_flags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TypeMount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TypeMount):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TypeMount):
            return True

        return self.to_dict() != other.to_dict()
