# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class UserSearch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'avatar': 'str',
        'country': 'str',
        'games': 'list[GameUserSearch]',
        'nickname': 'str',
        'player_id': 'str',
        'status': 'str',
        'verified': 'bool'
    }

    attribute_map = {
        'avatar': 'avatar',
        'country': 'country',
        'games': 'games',
        'nickname': 'nickname',
        'player_id': 'player_id',
        'status': 'status',
        'verified': 'verified'
    }

    def __init__(self, avatar=None, country=None, games=None, nickname=None, player_id=None, status=None, verified=None, _configuration=None):  # noqa: E501
        """UserSearch - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._avatar = None
        self._country = None
        self._games = None
        self._nickname = None
        self._player_id = None
        self._status = None
        self._verified = None
        self.discriminator = None

        if avatar is not None:
            self.avatar = avatar
        if country is not None:
            self.country = country
        if games is not None:
            self.games = games
        if nickname is not None:
            self.nickname = nickname
        if player_id is not None:
            self.player_id = player_id
        if status is not None:
            self.status = status
        if verified is not None:
            self.verified = verified

    @property
    def avatar(self):
        """Gets the avatar of this UserSearch.  # noqa: E501


        :return: The avatar of this UserSearch.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this UserSearch.


        :param avatar: The avatar of this UserSearch.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def country(self):
        """Gets the country of this UserSearch.  # noqa: E501


        :return: The country of this UserSearch.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this UserSearch.


        :param country: The country of this UserSearch.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def games(self):
        """Gets the games of this UserSearch.  # noqa: E501


        :return: The games of this UserSearch.  # noqa: E501
        :rtype: list[GameUserSearch]
        """
        return self._games

    @games.setter
    def games(self, games):
        """Sets the games of this UserSearch.


        :param games: The games of this UserSearch.  # noqa: E501
        :type: list[GameUserSearch]
        """

        self._games = games

    @property
    def nickname(self):
        """Gets the nickname of this UserSearch.  # noqa: E501


        :return: The nickname of this UserSearch.  # noqa: E501
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """Sets the nickname of this UserSearch.


        :param nickname: The nickname of this UserSearch.  # noqa: E501
        :type: str
        """

        self._nickname = nickname

    @property
    def player_id(self):
        """Gets the player_id of this UserSearch.  # noqa: E501


        :return: The player_id of this UserSearch.  # noqa: E501
        :rtype: str
        """
        return self._player_id

    @player_id.setter
    def player_id(self, player_id):
        """Sets the player_id of this UserSearch.


        :param player_id: The player_id of this UserSearch.  # noqa: E501
        :type: str
        """

        self._player_id = player_id

    @property
    def status(self):
        """Gets the status of this UserSearch.  # noqa: E501


        :return: The status of this UserSearch.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this UserSearch.


        :param status: The status of this UserSearch.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def verified(self):
        """Gets the verified of this UserSearch.  # noqa: E501


        :return: The verified of this UserSearch.  # noqa: E501
        :rtype: bool
        """
        return self._verified

    @verified.setter
    def verified(self, verified):
        """Sets the verified of this UserSearch.


        :param verified: The verified of this UserSearch.  # noqa: E501
        :type: bool
        """

        self._verified = verified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserSearch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserSearch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserSearch):
            return True

        return self.to_dict() != other.to_dict()
