# coding: utf-8

"""
    Data API

    # This API provide access to FACEIT's data  # noqa: E501

    OpenAPI spec version: 4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from faceit_api.configuration import Configuration


class UserSimple(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'avatar': 'str',
        'country': 'str',
        'faceit_url': 'str',
        'membership_type': 'str',
        'memberships': 'list[str]',
        'nickname': 'str',
        'skill_level': 'int',
        'user_id': 'str'
    }

    attribute_map = {
        'avatar': 'avatar',
        'country': 'country',
        'faceit_url': 'faceit_url',
        'membership_type': 'membership_type',
        'memberships': 'memberships',
        'nickname': 'nickname',
        'skill_level': 'skill_level',
        'user_id': 'user_id'
    }

    def __init__(self, avatar=None, country=None, faceit_url=None, membership_type=None, memberships=None, nickname=None, skill_level=None, user_id=None, _configuration=None):  # noqa: E501
        """UserSimple - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._avatar = None
        self._country = None
        self._faceit_url = None
        self._membership_type = None
        self._memberships = None
        self._nickname = None
        self._skill_level = None
        self._user_id = None
        self.discriminator = None

        if avatar is not None:
            self.avatar = avatar
        if country is not None:
            self.country = country
        if faceit_url is not None:
            self.faceit_url = faceit_url
        if membership_type is not None:
            self.membership_type = membership_type
        if memberships is not None:
            self.memberships = memberships
        if nickname is not None:
            self.nickname = nickname
        if skill_level is not None:
            self.skill_level = skill_level
        if user_id is not None:
            self.user_id = user_id

    @property
    def avatar(self):
        """Gets the avatar of this UserSimple.  # noqa: E501

        The Avatar of a user  # noqa: E501

        :return: The avatar of this UserSimple.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this UserSimple.

        The Avatar of a user  # noqa: E501

        :param avatar: The avatar of this UserSimple.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def country(self):
        """Gets the country of this UserSimple.  # noqa: E501

        The Country of a user  # noqa: E501

        :return: The country of this UserSimple.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this UserSimple.

        The Country of a user  # noqa: E501

        :param country: The country of this UserSimple.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def faceit_url(self):
        """Gets the faceit_url of this UserSimple.  # noqa: E501

        The FaceitUrl of a user  # noqa: E501

        :return: The faceit_url of this UserSimple.  # noqa: E501
        :rtype: str
        """
        return self._faceit_url

    @faceit_url.setter
    def faceit_url(self, faceit_url):
        """Sets the faceit_url of this UserSimple.

        The FaceitUrl of a user  # noqa: E501

        :param faceit_url: The faceit_url of this UserSimple.  # noqa: E501
        :type: str
        """

        self._faceit_url = faceit_url

    @property
    def membership_type(self):
        """Gets the membership_type of this UserSimple.  # noqa: E501

        Deprecated: use memberships instead  # noqa: E501

        :return: The membership_type of this UserSimple.  # noqa: E501
        :rtype: str
        """
        return self._membership_type

    @membership_type.setter
    def membership_type(self, membership_type):
        """Sets the membership_type of this UserSimple.

        Deprecated: use memberships instead  # noqa: E501

        :param membership_type: The membership_type of this UserSimple.  # noqa: E501
        :type: str
        """

        self._membership_type = membership_type

    @property
    def memberships(self):
        """Gets the memberships of this UserSimple.  # noqa: E501

        The Memberships of a user  # noqa: E501

        :return: The memberships of this UserSimple.  # noqa: E501
        :rtype: list[str]
        """
        return self._memberships

    @memberships.setter
    def memberships(self, memberships):
        """Sets the memberships of this UserSimple.

        The Memberships of a user  # noqa: E501

        :param memberships: The memberships of this UserSimple.  # noqa: E501
        :type: list[str]
        """

        self._memberships = memberships

    @property
    def nickname(self):
        """Gets the nickname of this UserSimple.  # noqa: E501

        The Nickname of a user  # noqa: E501

        :return: The nickname of this UserSimple.  # noqa: E501
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """Sets the nickname of this UserSimple.

        The Nickname of a user  # noqa: E501

        :param nickname: The nickname of this UserSimple.  # noqa: E501
        :type: str
        """

        self._nickname = nickname

    @property
    def skill_level(self):
        """Gets the skill_level of this UserSimple.  # noqa: E501

        The SkillLevel of a user  # noqa: E501

        :return: The skill_level of this UserSimple.  # noqa: E501
        :rtype: int
        """
        return self._skill_level

    @skill_level.setter
    def skill_level(self, skill_level):
        """Sets the skill_level of this UserSimple.

        The SkillLevel of a user  # noqa: E501

        :param skill_level: The skill_level of this UserSimple.  # noqa: E501
        :type: int
        """

        self._skill_level = skill_level

    @property
    def user_id(self):
        """Gets the user_id of this UserSimple.  # noqa: E501

        The ID of a user  # noqa: E501

        :return: The user_id of this UserSimple.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserSimple.

        The ID of a user  # noqa: E501

        :param user_id: The user_id of this UserSimple.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserSimple, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserSimple):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserSimple):
            return True

        return self.to_dict() != other.to_dict()
